const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const html = fs.readFileSync(__dirname + '/index.html', 'utf8');
const scripts = [...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m => m[1]).filter(s => s.trim());
scripts.forEach((s, i) => new vm.Script(s, {filename:'inline-' + i}));
function extract(name){
  const start = html.indexOf('function ' + name + '(');
  assert(start >= 0, name + ' exists');
  const next = html.indexOf('\nfunction ', start + 1);
  return html.slice(start, next);
}
const context = vm.createContext({URL, Intl, Date, Object, String});
['escapeHtml','escapeAttr','safeExternalUrl','todayISO'].forEach(name => vm.runInContext(extract(name), context));
assert.equal(context.todayISO(new Date('2026-10-03T17:00:00Z')), '2026-10-04');
assert.equal(context.todayISO(new Date('2026-10-03T16:59:59Z')), '2026-10-03');
assert.equal(context.todayISO(new Date('2028-02-28T17:00:00Z')), '2028-02-29');
assert.equal(context.escapeHtml(0), '0');
assert.equal(context.escapeAttr('"<&\''), '&quot;&lt;&amp;&#39;');
['javascript:alert(1)','data:text/html,hello','file:///secret','not a url'].forEach(url => assert.equal(context.safeExternalUrl(url), ''));
assert.equal(context.safeExternalUrl('https://example.com/?a=1&b=2'), 'https://example.com/?a=1&b=2');
assert.equal(context.safeExternalUrl('http://example.com'), 'http://example.com/');
const cardSource = extract('buildCard');
assert(!cardSource.includes('onclick="copyText('), 'Card copy values are not executable inline JS');
assert(cardSource.includes('data-card-copy="desc"'));
assert(html.includes('const useLatestDataExport = !parsed;'), 'Existing saved data takes precedence');
assert(html.includes("if(!localStorage.getItem('pctDashboardWebAppUrl_v2'))"), 'Dashboard URL is not reset on load');
const uiReminder = 'หมายเหตุ : หากมี Wallpaper สิ่งกีดขวางบริเวณติดตั้ง แนะนำให้ลูกค้าเคลียร์พื้นที่ให้เรียบร้อย หากเกิดความเสียหายจะไม่อยู่ในการดูแลของทางศูนย์บริการ';
assert.equal(html.split(uiReminder).length - 1, 1, 'Reminder exists only in the form markup');
assert(html.includes('class="crm-installation-reminder" style="color:#dc2626;'), 'Reminder is red');
const templateContext = vm.createContext({crmQuestionsFor:()=>['ข้อหนึ่ง','ข้อสอง','ข้อสาม'],toDMY:()=>'',CRM_REMINDER_TEXT:'Existing reminder'});
const templateStart = html.indexOf('function crmBuildColumnO(');
const templateEnd = html.indexOf('\nconst CRM_CUSTOMER_NOTE_TEXT_AIR',templateStart);
vm.runInContext(html.slice(templateStart,templateEnd), templateContext);
const copied = templateContext.crmBuildColumnO({productType:'air',answers:[],airFloor:'2',airOutdoor:'ภายนอก',airIndoor:'ภายใน'});
assert(!copied.includes(uiReminder), 'Copied template excludes UI-only reminder');
assert(copied.includes('- ชั้นที่ติดตั้ง: 2'), 'Existing answers remain in copied template');
console.log('PASS: ' + scripts.length + ' inline scripts parse; original tests + 4 reminder assertions pass.');
console.log('Browser smoke tests are separate; no production backend writes performed.');
